### ISSUE TITLE
portupgrade randomly just broke on a server

### ISSUE THREAD

**Issue by chrcoluk** [freebsd/portupgrade#70]
Crashed out during a install part of a port build, and now this comes up when running portupgrade with "ANY" arguments.

/usr/local/lib/ruby/site_ruby/2.4/pkgtools/pkgdbtools.rb:104:in `rescue in db_driver=': uninitialized constant PkgDBTools::DBError (NameError)
        from /usr/local/lib/ruby/site_ruby/2.4/pkgtools/pkgdbtools.rb:63:in `db_driver='
        from /usr/local/lib/ruby/site_ruby/2.4/pkgtools/portsdb.rb:168:in `setup'
        from /usr/local/lib/ruby/site_ruby/2.4/pkgtools/pkgtools.rb:242:in `init_pkgtools_global'
        from /usr/local/sbin/portupgrade:531:in `block in main'
        from /usr/local/lib/ruby/2.4/optparse.rb:1062:in `initialize'
        from /usr/local/sbin/portupgrade:238:in `new'
        from /usr/local/sbin/portupgrade:238:in `main'
        from /usr/local/sbin/portupgrade:2380:in `<main>'

I have rebuilt all dependencies but still the same issue.

In addition I can never get portupgrade to use anything but bdb even tho thats apparently not the preferred database to use.

FreeBSD 11.1

**Comment by ohreally** [comment]
I know this is really old, but since this issue is still open, and I just ran into this problem while upgrading from 13.3-RELEASE to 14.1-RELEASE, and this was my only hit for this problem in DuckDuckGo, I'll quickly describe what solved this for me.

```
# cd /usr/ports/databases/ruby-bdb
# make
# make deinstall && make reinstall
# make clean
# cd /usr/ports/ports-mgmt/portupgrade
# make
# make deinstall && make reinstall
# make clean
```

I'm not even sure if it's necessary to reinstall portupgrade, but at least it works again.
